In [4]:
# Importing NumPy Library
import numpy as np
import sys

def GaussJordan(A):
    n = len(A)

    # Making numpy array of n size and initializing
    # to zero for storing solution vector
    x = np.zeros(n)

    # Applying Gauss Jordan Elimination
    print("Step Gauss Jordan Elimination")
    for i in range(n):
        if A[i][i] == 0.0:
            sys.exit('Divide by zero detected!')

        for j in range(n):
            if i != j:
                ratio = A[j][i]/A[i][i]

                for k in range(n+1):
                    A[j][k] = A[j][k] - ratio * A[i][k]
        print(f"step {i+1}")
        for row in A:
            print(f"[{', '.join([f'{value:.2f}' for value in row])}],")

    print()
    for i in range(n):
        x[i] = A[i][n]/A[i][i]
        print(f"memasukkan hasil x{i}")
        print(x)

    # Displaying solution
    print('\nRequired solution is: ')
    for i in range(n):
        print('X%d = %0.2f' %(i,x[i]), end = '\t')
    print("\n\n")

# input 1
print("input 1")
A = np.array ([[ 1, 1,  0,  3, 4],
            [ 2, 1,  -1, 1, 1],
            [ 3,  -1,  -1,  2, -3],
            [ -1,  2,  3,  -1, 4]])
A = A.astype(float)
GaussJordan(A)

# input 2
print("input 2")
B = np.array ([[ 1, 1,  2,  9],
            [ 2, 4,  -3, 1],
            [ 3,  6,  -5,  0]])
B = B.astype(float)
GaussJordan(B)


input 1
Step Gauss Jordan Elimination
step 1
[1.00, 1.00, 0.00, 3.00, 4.00],
[0.00, -1.00, -1.00, -5.00, -7.00],
[0.00, -4.00, -1.00, -7.00, -15.00],
[0.00, 3.00, 3.00, 2.00, 8.00],
step 2
[1.00, 0.00, -1.00, -2.00, -3.00],
[0.00, -1.00, -1.00, -5.00, -7.00],
[0.00, 0.00, 3.00, 13.00, 13.00],
[0.00, 0.00, 0.00, -13.00, -13.00],
step 3
[1.00, 0.00, 0.00, 2.33, 1.33],
[0.00, -1.00, 0.00, -0.67, -2.67],
[0.00, 0.00, 3.00, 13.00, 13.00],
[0.00, 0.00, 0.00, -13.00, -13.00],
step 4
[1.00, 0.00, 0.00, 0.00, -1.00],
[0.00, -1.00, 0.00, 0.00, -2.00],
[0.00, 0.00, 3.00, 0.00, 0.00],
[0.00, 0.00, 0.00, -13.00, -13.00],

memasukkan hasil x0
[-1.  0.  0.  0.]
memasukkan hasil x1
[-1.  2.  0.  0.]
memasukkan hasil x2
[-1.  2.  0.  0.]
memasukkan hasil x3
[-1.  2.  0.  1.]

Required solution is: 
X0 = -1.00	X1 = 2.00	X2 = 0.00	X3 = 1.00	


input 2
Step Gauss Jordan Elimination
step 1
[1.00, 1.00, 2.00, 9.00],
[0.00, 2.00, -7.00, -17.00],
[0.00, 3.00, -11.00, -27.00],
step 2
[1.00, 0.00, 5.50, 17.50],